more config

diff --git a/install/makesd b/install/makesd
--- a/install/makesd
+++ b/install/makesd
@@ -18,46 +18,53 @@ if [ ! -e $dev ]; then
     exit 1
 fi
 
-if [ "$OK" == '' ]; then
-    lsblk -f $dev
-    echo -n "We are going to rewrite the entire device, ok? yN: "
-    read ok
-    if [[ "$ok" != 'y' && $ok != 'Y' ]]; then
-        echo "aborted"
-        exit 2
-    fi
-fi
-
 if [ $UID != 0 ]; then
     sudo -p 'sudo for disk ops, passwd: ' env OK=1 $0 $dev
     exit $?
 fi
 
-echo "rooting.."
+if [ "$1" == "--init" ]; then
+    if [ "$OK" == '' ]; then
+        lsblk -f $dev
+        echo -n "We are going to rewrite the entire device, ok? yN: "
+        read ok
+        if [[ "$ok" != 'y' && $ok != 'Y' ]]; then
+            echo "aborted"
+            exit 2
+        fi
+    fi
 
-if mount -l | grep $dev >/dev/null; then
-    echo "unmounting..."
-    lsblk -l -n -o NAME | xargs --no-run-if-empty -n 1 -ix umount /dev/x
+    echo "rooting.."
+
+    if mount -l | grep $dev >/dev/null; then
+        echo "unmounting..."
+        lsblk -l -n -o NAME | xargs --no-run-if-empty -n 1 -ix umount /dev/x
+    fi
+
+    args="dd status=progress bs=4M if=$img of=$dev"
+    echo
+    echo $args
+    echo -n "Confirm that yN: "
+    read ok
+    if [[ "$ok" != 'y' && $ok != 'Y' ]]; then
+        echo "aborted"
+        exit 2
+    fi
+    $args
+
+    lsblk -f /dev/mmcblk0
 fi
 
-args="dd status=progress bs=4M if=$img of=$dev"
-echo
-echo $args
-echo -n "Confirm that yN: "
-read ok
-if [[ "$ok" != 'y' && $ok != 'Y' ]]; then
-    echo "aborted"
-    exit 2
-fi
-$args
-lsblk -f /dev/mmcblk0
 
 # Mount
 
+set -x
 rootfs=/dev/`lsblk -l -o NAME,FSTYPE,TYPE -n $dev | egrep -v ' vfat| disk' | awk '{print $1}'`
 dir=/mnt/pimnt
 mkdir -p $dir
-mount $rootfs $dir
+if ! mount -l | grep $dev >/dev/null; then
+    mount $rootfs $dir
+fi
 lsblk -f $dev
 
 echo -n "Which pi: 1|2 "
